# Generated by Django 5.2.8 on 2025-11-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=128, verbose_name='Улица')),
                ('house', models.CharField(max_length=32, verbose_name='Дом')),
                ('name', models.CharField(max_length=128, verbose_name='Имя')),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('current_services', models.CharField(choices=[('mobile', 'Мобильная связь'), ('copper', 'Медный телефон')], max_length=32, verbose_name='Текущие услуги')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
