# Generated by Django 5.2.8 on 2025-11-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyrequest',
            name='settlement_custom',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Свой населённый пункт'),
        ),
    ]
