# Generated by Django 5.2.8 on 2025-11-19 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_surveyrequest_settlement_custom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyrequest',
            name='settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='surveys', to='survey.settlement', verbose_name='Населённый пункт'),
        ),
    ]
