# Generated by Django 5.2.8 on 2025-11-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_alter_surveyrequest_settlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyrequest',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Номер квартиры'),
        ),
    ]
